### ISSUE TITLE
Feature Request: Include elevation

### ISSUE THREAD

**Issue by s-oliver** [Hypercubesoft/HCKalmanFilter#1]
This is a superb library for filtering raw location data, thanks for providing it.
For activity tracking not only latitude and longitude are relevant, but also the current elevation. It would be great if you'd filter and return that aswell.

**Comment by Hypercubesoft** [comment]
Hi,
Glad to hear that you like it. We are going to add new features soon. Will have elevation data filtering on mind. This was used for an internal project that we did and we had no use of elevation data.
Best Regards,
Hypercube
