### ISSUE TITLE
Performance when post-processing

### ISSUE THREAD

**Issue by georgbachmann** [Hypercubesoft/HCKalmanFilter#10]
Hello,
today I tried out your kalman filter and it looks pretty promising. The only issue I have is that even on my MacBook Pro post-processing like 2000 points takes about 5 seconds...
Do you have any plans on optimizing performance? From what I've seen in Instruments it's mainly the Matrix inverse and multiply functions as well as + and - (but far less)

Cheers,
Georg

**Comment by georgbachmann** [comment]
I just replaced your HCMatrixObject with Mattt Thompson brilliant Surge-Matrix implementation. Now it's super blazing fast!!! :)

**Comment by zhangchunzc** [comment]
Has objective-c version?

**Comment by Hypercubesoft** [comment]
Hi georgbachmann,
Will you be able to do pull request with changes you made so other users can have some performance? It would save us time if we done need to write it now when you done it :)

@zhangchunzc
Right now we have just swift version. I think there are kalman filter implementations in Objective-C. We didnt find one for swift when we needed it so we wrote this one :)

**Comment by Hypercubesoft** [comment]
In the latest version we have added Mattt Thompson brilliant Surge-Matrix, so now we have improved the performance. 
Thx @georgbachmann
