### ISSUE TITLE
I can't build it

### ISSUE THREAD

**Issue by RyanSprite** [Hypercubesoft/HCKalmanFilter#11]
I download the zip and pod install.
when i build it,Xcode reports Use of undeclared type 'HCKalmanAlgoorithm' in MapService.swift.
How can i resolve it?

**Comment by lazar89nis** [comment]
Hi,
We will fix this bug next week. At last commit, we broke test project. Just go to Build Phases and add to Compile Sources HCKalmanAlgorithm.swift and HCMatrixObject.swift.
That will fix problem until we update source

**Comment by Hypercubesoft** [comment]
Hi,
We will fix this bug next week. At last commit, we broke test project. Just go to Build Phases and add to Compile Sources HCKalmanAlgorithm.swift and HCMatrixObject.swift.
That will fix problem until we update source

**Comment by Cleverbum** [comment]
I need to learn to read these posts before trying to fix things myself... look forward to the fix, and have just applied the workaround

**Comment by Hypercubesoft** [comment]
Please check our latest version, this issue has been fixed. If you have some problems again, please contact us.
