### ISSUE TITLE
Use of kCLLocationAccuracyBestForNavigation

### ISSUE THREAD

**Issue by jeffbailey** [Hypercubesoft/HCKalmanFilter#12]
First of all, thanks very much for sharing this with the world. It works great an allows to smooth workout routes. However, I noticed the locations it creates uses kCLLocationAccuracyBestForNavigation for horizontal and vertical accuracy.  That actually makes the location invalid since it has a value of -2 and Apple considers anything less than zero to be invalid.  I changed it to the following:

`        let kalmanCLLocation = CLLocation(coordinate: CLLocationCoordinate2D(latitude: lat,longitude: lon), altitude: altitude, horizontalAccuracy: self.previousLocation.horizontalAccuracy, verticalAccuracy: self.previousLocation.verticalAccuracy, timestamp: previousMeasureTime)`

**Comment by Hypercubesoft** [comment]
Hi @jeffbailey 
Thank you for contacting us, we have found the problem and we have fixed it. Please pull the latest version and let us know if you have some problems again.
