### ISSUE TITLE
Distortion of initial GPS points in a trip

### ISSUE THREAD

**Issue by talkingkarthik** [Hypercubesoft/HCKalmanFilter#2]
Thanks for the good work! In my testing, this filter works well when driving at a consistent speed after the initial acceleration from zero to say 20 mph. However, when the trip starts and the car is still either stationary or moving at <5 mph, and the GPS signals are not extremely accurate/wavering, the filter seems to amplify the effect of the GPS location-points noise.

**Comment by Hypercubesoft** [comment]
Hello talkingkarthik,
Thanks for the feedback. There are some border cases which we left unimplemented like stationary or accuracy dropped. Those are the cases that can be implemented differently depending on the case you are working on. In some cases, accuracy drop should disable tracking or in some other, it should just ignore that location. Also in some cases, stationary should mean that you have completed the movement and should stop the tracking. Our main goal was to implement Kalman Filter so it can be upgraded and used in as many as possible cases. 
Best Regards,
Hypercube
