### ISSUE TITLE
Build Error Xcode 9 (9A235)

### ISSUE THREAD

**Issue by divgunsingh** [Hypercubesoft/HCKalmanFilter#9]
The project is not building in Xcode 9.
Error Below ->

<img width="885" alt="screen shot 2017-09-28 at 3 13 30 pm" src="https://user-images.githubusercontent.com/4990903/30960153-cce5273e-a45f-11e7-893f-c18b90683c81.png">

**Comment by Hypercubesoft** [comment]
Hi,
what version of pod are you using? Its fixed in new version.
